version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: database.Dockerfile
    container_name: lunary-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optional: expose db port to host
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: lunary-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      NODE_ENV: production
      PORT: 3001
      JWT_SECRET: secret # Default secret for testing
      # BACKEND_URL: http://localhost:3001 # Might be needed by the app
      # Add other required ENV VARS here if discovered
    depends_on:
      db:
        condition: service_healthy # Wait for db to be healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:3001/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s # Give backend more time to start

volumes:
  postgres_data:
