services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-service
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - dind-data:/var/lib/docker
    networks:
      - app-network
    environment:
      - HELM_API_KEY=${HELM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: frontend-service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dind-data:
    external: true
