apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arm64-compatible
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
