apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
      containers:
      - name: backend
        image: us-west1-docker.pkg.dev/soe-ai-cyber/bountyagent/backend-image:ui
        ports:
        - containerPort: 7999
        securityContext:
          privileged: true  # Required for Docker-in-Docker
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        - name: logs
          mountPath: /app/logs
        envFrom:
        - secretRef:
            name: app-secrets
      volumes:
      - name: dind-storage
        emptyDir: {}
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 7999
    targetPort: 7999
