name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Check for label to run all tests
        id: check_label
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name' 2>/dev/null || echo "")
          echo "Labels: $labels"
          if echo "$labels" | grep -q "run all tests"; then
            echo "::set-output name=all_tests::true"
          else
            echo "::set-output name=all_tests::false"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --cache-dir ~/.cache/pip
      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token  

        - name: Run backend tests with coverage
            run: |
              if [[ "${{ steps.check_label.outputs.all_tests }}" == "true" ]]; then
                coverage run -m tests.runner
              elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
                git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} > changed_files.txt
                coverage run -m tests.runner $(cat changed_files.txt)
              else
                coverage run -m tests.runner
              fi
              coverage report

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          if [[ "${{ steps.check_label.outputs.all_tests }}" == "true" ]]; then
            npm test  # Run all tests
          elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
            git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} > changed_files.txt
            npm test -- --findRelatedTests $(cat changed_files.txt)
          else
            npm test  # Run all tests
          fi